title: Epicycle.ImageProcessing (.NET)
url: https://github.com/open-epicycle/Epicycle.ImageProcessing-cs
summary: "Epicycle .NET image processing library. Includes: Convolution matrix, Sobel operator, Gaussian blur"

organization: Epicycle
tags: epicycle lib library image processing convolution matrix sobel operator gaussian blur filter
copyright: Copyright 2015 Epicycle
license_url: http://www.apache.org/licenses/LICENSE-2.0

release_notes: https://github.com/open-epicycle/Epicycle.ImageProcessing-cs/blob/ver-$version$/README.md

dotnet_frameworks:
 - net35
 - net40
 - net45

nuget_dependencies:
 - Epicycle.Commons-cs.0.1.8.0
 - Epicycle.Math-cs.0.1.6.0
 - Epicycle.Graphics-cs.0.1.6.0

description: |
   Epicycle .NET image processing library. Includes: Convolution matrix, Sobel operator, Gaussian blur
   
   * Details & release notes: https://github.com/open-epicycle/Epicycle.ImageProcessing-cs/blob/ver-$version$/README.md
   * Sources: https://github.com/open-epicycle/Epicycle.ImageProcessing-cs/tree/ver-$version$
   * Git repository: https://github.com/open-epicycle/Epicycle.ImageProcessing-cs